### ISSUE TITLE
Pointless example usage

### ISSUE THREAD

**Issue by eligrey** [WICG/purification#24]
The "example usage" in the explainer does not actually affect the security properties of the code in question.

Your example actually encourages random censorship of HTML strings for no reason instead of rendering the HTML as an inert string, which is what the `textContent` setter would have done.

What's the point of this example? Was `innerHTML` meant to be used instead?

```js
document.getElementById("...").textContent =
  sanitizers.html.toString(user_supplied_value);
```

**Comment by mozfreddyb** [comment]
Thanks!
