### ISSUE TITLE
Context and meaning of "sanitized"

### ISSUE THREAD

**Issue by SMotaal** [WICG/purification#4]
Can we consider more concretely what the context and meaning of "sanitized" looks like in this and referenced efforts.

- For sanity to hold, branding something "safe" should do so in ways that align with the semantics of the branded entities — ie `makeSafe('<link href=x/>') === '<link href=x/>'` then it is only natural to expect `isSafe(makeSafe('<link href=x/>')) === isSafe('<link href=x/>')`.

- For safety to hold, branding something "safe" does not mean that it cannot be unsafe in the wrong capacity — ie injected in the wrong place, or at the very least being exposed to a masquerading API/sink.

Those are some aspects I know I am hoping to preserve when branding something safe.

I am sure a lot of consideration has gone into this already, and maybe I missed some aspects in the current draft, so is there a good way to address this dimension more visibly?

**Comment by cure53** [comment]
Heya, the idea of what safe means in the context of sanitization is described here:
https://github.com/WICG/purification#wait-what-does-secure-even-mean-in-this-context

More specifics are mentioned here:
https://github.com/cure53/DOMPurify/wiki/Security-Goals-&-Threat-Model

**Comment by SMotaal** [comment]
@cure53 thanks for that — but I think I am failing to elaborate my concern (sorry) which is not about what would content would constitute a sanitized string (versus one needing of sanitization) and more about related proposals (TrustedTypes) distinguishing between one that has been "blessed" somehow, and if that same literal value is/can/should be "blessed" because it is the literal, a branded instance or the same literal… all this has very different implications from the JS developer's side (especially if they are not privy to implementation details like branding with internal fields)

**Comment by cure53** [comment]
I think the goal here is a much smaller than what TrustedTypes is aiming for. To refer to your initial example, we aim to provide a `makeSafe()` but not an `isSafe()`.

We essentially wanna bring the tradecraft of sanitizing strings that is being done, typically, by servers and external JS libraries, such as our own, to a place where we believe it belongs - the user agent itself.

**Comment by SMotaal** [comment]
Thanks for clarifying! I think that this is a well-defined scope with a very specific objective, so it is not branding something safe, merely `use(makeSafe(anything))`.

It might be just me, but maybe others out there would find this distinction useful in the README… just a thought that might not be helpful all the same 😄

**Comment by cure53** [comment]
Most welcome, and yes, it might make sense to add a section that describes how we compare to more complex approaches such as TrustedTypes, will add soon, thanks :)
