### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/purification#5]
HI @mozfreddyb, just checking if this is still something you want to keep pursuing? It hasn't moved for about a year so wondering if we should archive it?

**Comment by mozfreddyb** [comment]
This is somewhere on the backburner for me, but I want this to happen.

My next step would be helping browsers converge what and how they sanitize HTML on paste. Once that's somewhat clear, we can write it down as the algorithm. 

The good news is that WebKit and Firefox seem to allow the same set of HTML elements. Chrome seems a bit more permissive. I've done black box testing at https://github.com/freddyb/copypaste2 but probably need to start talking to the right engineers to open the box and turn it into a whitebox discussion.

**Comment by marcoscaceres** [comment]
Ok, will leave it open for now and check in again in a few months. Let us @WICG/chairs know if we can be of help in reaching out to anyone.
